// src/services/maintenanceService.js
// Schema ref:
// maintenance_orders: id, wo_number(auto), location NN, room_id, category, description NN,
//   priority('normal'), status('open'), reported_by, assigned_to, resolution,
//   cost(0), started_at, resolved_at, created_at, updated_at
// assets: id, name NN, category, location, serial_number, purchase_date, purchase_cost(0),
//   warranty_expiry, last_serviced, next_service_due, status('operational'), notes, created_at, updated_at
// NOTE: wo_number auto-generated by trg_wo_number trigger

import { supabase } from '../config/supabase.js';
import { AppError } from '../middleware/errorHandler.js';

// ─── Work Orders ──────────────────────────────────────────

export const getAllWorkOrders = async (filters = {}, page = 1, limit = 20) => {
  const from = (page - 1) * limit;
  const to   = from + limit - 1;

  let query = supabase
    .from('maintenance_orders')
    .select(`
      id, wo_number, location, category, description, priority, status,
      resolution, cost, started_at, resolved_at, created_at,
      rooms ( id, number, floor ),
      reporter:reported_by ( id, full_name ),
      assignee:assigned_to ( id, full_name )
    `, { count: 'exact' })
    .order('created_at', { ascending: false });

  if (filters.status)      query = query.eq('status', filters.status);
  if (filters.priority)    query = query.eq('priority', filters.priority);
  if (filters.category)    query = query.eq('category', filters.category);
  if (filters.room_id)     query = query.eq('room_id', filters.room_id);
  if (filters.assigned_to) query = query.eq('assigned_to', filters.assigned_to);

  const { data, error, count } = await query.range(from, to);
  if (error) throw new AppError(`Failed to fetch work orders: ${error.message}`, 500);
  return { data, total: count };
};

export const getWorkOrderById = async (id) => {
  const { data, error } = await supabase
    .from('maintenance_orders')
    .select(`
      id, wo_number, location, category, description, priority, status,
      resolution, cost, started_at, resolved_at, created_at, updated_at,
      rooms ( id, number, floor ),
      reporter:reported_by ( id, full_name ),
      assignee:assigned_to ( id, full_name )
    `)
    .eq('id', id)
    .single();

  if (error || !data) throw new AppError('Work order not found.', 404);
  return data;
};

export const createWorkOrder = async (payload, reportedBy) => {
  const { location, room_id, category, description, priority, assigned_to, cost } = payload;

  // If room_id provided verify room exists
  if (room_id) {
    const { data: room } = await supabase
      .from('rooms')
      .select('id')
      .eq('id', room_id)
      .eq('is_deleted', false)
      .single();

    if (!room) throw new AppError('Room not found.', 404);
  }

  const { data, error } = await supabase
    .from('maintenance_orders')
    .insert({
      location,
      room_id:     room_id     || null,
      category:    category    || null,
      description,
      priority:    priority    || 'normal',
      status:      'open',
      reported_by: reportedBy,
      assigned_to: assigned_to || null,
      cost:        cost        || 0,
    })
    .select()
    .single();

  if (error) throw new AppError(`Failed to create work order: ${error.message}`, 500);
  return data;
};

export const updateWorkOrder = async (id, payload) => {
  await getWorkOrderById(id);

  const { data, error } = await supabase
    .from('maintenance_orders')
    .update(payload)
    .eq('id', id)
    .select()
    .single();

  if (error) throw new AppError(`Failed to update work order: ${error.message}`, 500);
  return data;
};

export const assignWorkOrder = async (id, assignedTo, assignedBy) => {
  await getWorkOrderById(id);

  const { data: user } = await supabase
    .from('users')
    .select('id, full_name')
    .eq('id', assignedTo)
    .single();

  if (!user) throw new AppError('Assigned user not found.', 404);

  const { data, error } = await supabase
    .from('maintenance_orders')
    .update({ assigned_to: assignedTo })
    .eq('id', id)
    .select()
    .single();

  if (error) throw new AppError(`Failed to assign work order: ${error.message}`, 500);
  return data;
};

export const startWorkOrder = async (id) => {
  const wo = await getWorkOrderById(id);

  if (wo.status !== 'open') {
    throw new AppError(`Cannot start a work order with status: ${wo.status}.`, 409);
  }

  const { data, error } = await supabase
    .from('maintenance_orders')
    .update({ status: 'in_progress', started_at: new Date().toISOString() })
    .eq('id', id)
    .select()
    .single();

  if (error) throw new AppError(`Failed to start work order: ${error.message}`, 500);
  return data;
};

export const resolveWorkOrder = async (id, resolution, cost) => {
  const wo = await getWorkOrderById(id);

  if (!['open', 'in_progress'].includes(wo.status)) {
    throw new AppError(`Cannot resolve a work order with status: ${wo.status}.`, 409);
  }

  const { data, error } = await supabase
    .from('maintenance_orders')
    .update({
      status:      'resolved',
      resolution,
      cost:        cost || wo.cost,
      resolved_at: new Date().toISOString(),
    })
    .eq('id', id)
    .select()
    .single();

  if (error) throw new AppError(`Failed to resolve work order: ${error.message}`, 500);
  return data;
};

export const closeWorkOrder = async (id) => {
  const wo = await getWorkOrderById(id);

  if (wo.status !== 'resolved') {
    throw new AppError('Only resolved work orders can be closed.', 409);
  }

  const { data, error } = await supabase
    .from('maintenance_orders')
    .update({ status: 'closed' })
    .eq('id', id)
    .select()
    .single();

  if (error) throw new AppError(`Failed to close work order: ${error.message}`, 500);
  return data;
};

// ─── Assets ───────────────────────────────────────────────

export const getAllAssets = async (filters = {}, page = 1, limit = 20) => {
  const from = (page - 1) * limit;
  const to   = from + limit - 1;

  let query = supabase
    .from('assets')
    .select('*', { count: 'exact' })
    .order('name');

  if (filters.status)   query = query.eq('status', filters.status);
  if (filters.category) query = query.eq('category', filters.category);
  if (filters.location) query = query.ilike('location', `%${filters.location}%`);

  const { data, error, count } = await query.range(from, to);
  if (error) throw new AppError(`Failed to fetch assets: ${error.message}`, 500);
  return { data, total: count };
};

export const getAssetById = async (id) => {
  const { data, error } = await supabase
    .from('assets')
    .select('*')
    .eq('id', id)
    .single();

  if (error || !data) throw new AppError('Asset not found.', 404);
  return data;
};

export const createAsset = async (payload) => {
  const { data, error } = await supabase
    .from('assets')
    .insert(payload)
    .select()
    .single();

  if (error) throw new AppError(`Failed to create asset: ${error.message}`, 500);
  return data;
};

export const updateAsset = async (id, payload) => {
  await getAssetById(id);

  const { data, error } = await supabase
    .from('assets')
    .update(payload)
    .eq('id', id)
    .select()
    .single();

  if (error) throw new AppError(`Failed to update asset: ${error.message}`, 500);
  return data;
};

export const deleteAsset = async (id) => {
  await getAssetById(id);

  const { error } = await supabase
    .from('assets')
    .delete()
    .eq('id', id);

  if (error) throw new AppError(`Failed to delete asset: ${error.message}`, 500);
  return { message: 'Asset deleted successfully.' };
};

export const getAssetsDueForService = async () => {
  const today = new Date().toISOString().split('T')[0];

  const { data, error } = await supabase
    .from('assets')
    .select('id, name, category, location, last_serviced, next_service_due, status')
    .lte('next_service_due', today)
    .eq('status', 'operational')
    .order('next_service_due');

  if (error) throw new AppError(`Failed to fetch assets due for service: ${error.message}`, 500);
  return data;
};